comment:
  layout: "header, diff, flags, components"

component_management:
  individual_components:
    - component_id: plugin_hardcover
      name: hardcover
      paths:
        - plugins/hardcover/**
    - component_id: plugin_anilist
      name: anilist
      paths:
        - plugins/anilist/**
    - component_id: lib_common
      name: common
      paths:
        - libs/common/**
    - component_id: lib_graphql
      name: graphql
      paths:
        - libs/graphql/**
