# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.4
    hooks:
      # Run the linter.
      - id: ruff
        stages: [pre-commit]
      # Run the formatter.
      - id: ruff-format
        stages: [pre-commit]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.2
    hooks:
      # Update the uv lockfile
      - id: uv-lock
