[tools]
python = "3.13.1"
task = "latest"
uv = "latest"
yq = "latest"
git-cliff = "latest"

[env]
CALIBRE_HOME = "{{config_root}}/.calibre"
CALIBRE_CONFIG_DIRECTORY = "{{env.CALIBRE_HOME}}/config"
CALIBRE_LIBRARY = "{{env.CALIBRE_HOME}}/library"
CALIBRE_DEVELOP_FROM = "{{env.CALIBRE_HOME}}/source/src"
PYTHONPATH = "{{env.CALIBRE_DEVELOP_FROM}}"
_.python.venv = ".venv"

[settings.python]
uv_venv_auto = true
