name: Install Dependencies
description: Install required dependencies to run the project
runs:
  using: "composite"
  steps:
    - name: Install tools from mise
      uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4

    - name: Install calibre dependencies
      shell: bash
      run: sudo apt-get install -y libegl1 libopengl0 libxcb-cursor0

    - name: Install calibre
      shell: bash
      run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

    - name: Install the project
      shell: bash
      run: task install
