name: "Test"

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-packages --dev

      - name: Run Unit Tests
        uses: pavelzw/pytest-action@v2.2.0
        with:
          emoji: false
          verbose: false
          job-summary: true
